name: nordigen-java-api Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test_push_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure application properties1
        run: echo "token.secret.id=${{secrets.TOKEN_SECRET_ID}}" >> src/test/resources/application.properties
      - name: Configure application properties2
        run: echo "token.secret.key=${{secrets.TOKEN_SECRET_KEY}}" >> src/test/resources/application.properties
      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package
